### ISSUE TITLE
i would like to contribute to ur open sourced project. 

### ISSUE THREAD

**Issue by shauryabit2k18** [kushrike/BITInsider#1]
https://github.com/shauryabit2k18/facemash
plz reffer to this i would like to contribute to ur project to make if a fully functional app where u could even get all the details of a person with just a pic that they will upload to the interface and the app will then scan for a similar face from all the pictures that we can scrape off from insta facebook.

i think it will be a interesting and fully functional application to work on

**Comment by kushrike** [comment]
Go on. Fork the repo and make suitable changes.
